runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static.*
  static_dir: static
  application_readable: True
- url: /audio.*
  static_dir: audio
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
