runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static.*
  static_dir: static
  application_readable: True
- url: /audio.*
  static_dir: audio
  application_readable: True
# Doesn't need to be included (I think it's because HTML that needs rendering won't appear correctly)
# - url: /templates.*
#   static_dir: templates
#   application_readable: True
- url: /images.*
  static_dir: images
  application_readable: True
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
